name: license_scanner_ui
description: User interface for License Scanner Service

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.2+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  cupertino_icons: ^1.0.1+1
  responsive_framework: ^0.0.14
  smooth_page_indicator: ^0.2.0
  provider: ^4.3.2+2
  http: ^0.13.5
  dio: ^5.0.3
  url_launcher: ^5.7.10
  toast: ^0.1.5
  badges: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

